### ISSUE TITLE
how to set webhook?

### ISSUE THREAD

**Issue by ghost** [Ardakilic/Telegram-bot-php#4]
hi

how to set webhook ? 

i open this http://localhost:8080/set_webhook/**bothook**

and show error

please help me

**Comment by Ardakilic** [comment]
What error are you getting?

**Comment by ghost** [comment]
http://uupload.ir/files/tjzm_aaa.png

**Comment by Ardakilic** [comment]
This is because of these errors:
- This app needs to run on port 80 or 443 (ssl)
- You're trying to run this from localhost (check the bothook link in image at line 13, the "localhost" is fethed automatically), this won't work. Telegram can't simply post to "your localhost".
-  Because of the SSL certificate. You need not a self signed, but a totally working, "green" ssl certificate and you need to run this on a live server for this to work.

**Comment by ghost** [comment]
oh yes thank you
:+1:

**Comment by Ardakilic** [comment]
You're welcome!

Closing this for now. Feel free to open a new issue if you encounter any more errors.
